#ifndef _COLORS_H
#define _COLORS_H

enum
{
	SCREEN_ATTR_CGA_FG_BLACK         = 0x00,
	SCREEN_ATTR_CGA_FG_BLUE          = 0x01,
	SCREEN_ATTR_CGA_FG_GREEN         = 0x02,
	SCREEN_ATTR_CGA_FG_CYAN          = 0x03,
	SCREEN_ATTR_CGA_FG_RED           = 0x04,
	SCREEN_ATTR_CGA_FG_MAGENTA       = 0x05,
	SCREEN_ATTR_CGA_FG_BROWN         = 0x06,
	SCREEN_ATTR_CGA_FG_LIGHT_GRAY    = 0x07,

	SCREEN_ATTR_FG_LIGHT             = 0x08,

	SCREEN_ATTR_CGA_FG_DARK_GRAY     = SCREEN_ATTR_FG_LIGHT | SCREEN_ATTR_CGA_FG_BLACK,
	SCREEN_ATTR_CGA_FG_LIGHT_BLUE    = SCREEN_ATTR_FG_LIGHT | SCREEN_ATTR_CGA_FG_BLUE,
	SCREEN_ATTR_CGA_FG_LIGHT_GREEN   = SCREEN_ATTR_FG_LIGHT | SCREEN_ATTR_CGA_FG_GREEN,
	SCREEN_ATTR_CGA_FG_LIGHT_CYAN    = SCREEN_ATTR_FG_LIGHT | SCREEN_ATTR_CGA_FG_CYAN,
	SCREEN_ATTR_CGA_FG_LIGHT_RED     = SCREEN_ATTR_FG_LIGHT | SCREEN_ATTR_CGA_FG_RED,
	SCREEN_ATTR_CGA_FG_LIGHT_MAGENTA = SCREEN_ATTR_FG_LIGHT | SCREEN_ATTR_CGA_FG_MAGENTA,
	SCREEN_ATTR_CGA_FG_YELLOW        = SCREEN_ATTR_FG_LIGHT | SCREEN_ATTR_CGA_FG_BROWN,
	SCREEN_ATTR_CGA_FG_WHITE         = SCREEN_ATTR_FG_LIGHT | SCREEN_ATTR_CGA_FG_LIGHT_GRAY,

	SCREEN_ATTR_CGA_BG_BLACK         = SCREEN_ATTR_CGA_FG_BLACK << 4,
	SCREEN_ATTR_CGA_BG_BLUE          = SCREEN_ATTR_CGA_FG_BLUE << 4,
	SCREEN_ATTR_CGA_BG_GREEN         = SCREEN_ATTR_CGA_FG_GREEN << 4,
	SCREEN_ATTR_CGA_BG_CYAN          = SCREEN_ATTR_CGA_FG_CYAN << 4,
	SCREEN_ATTR_CGA_BG_RED           = SCREEN_ATTR_CGA_FG_RED << 4,
	SCREEN_ATTR_CGA_BG_MAGENTA       = SCREEN_ATTR_CGA_FG_MAGENTA << 4,
	SCREEN_ATTR_CGA_BG_BROWN         = SCREEN_ATTR_CGA_FG_BROWN << 4,
	SCREEN_ATTR_CGA_BG_LIGHT_GRAY    = SCREEN_ATTR_CGA_FG_LIGHT_GRAY << 4,
	// note: these are only available if blinking is disabled
	SCREEN_ATTR_BG_LIGHT             = 0x80,
	SCREEN_ATTR_CGA_BG_DARK_GRAY     = SCREEN_ATTR_CGA_FG_DARK_GRAY << 4,
	SCREEN_ATTR_CGA_BG_LIGHT_BLUE    = SCREEN_ATTR_CGA_FG_LIGHT_BLUE << 4,
	SCREEN_ATTR_CGA_BG_LIGHT_GREEN   = SCREEN_ATTR_CGA_FG_LIGHT_GREEN << 4,
	SCREEN_ATTR_CGA_BG_LIGHT_CYAN    = SCREEN_ATTR_CGA_FG_LIGHT_CYAN << 4,
	SCREEN_ATTR_CGA_BG_LIGHT_RED     = SCREEN_ATTR_CGA_FG_LIGHT_RED << 4,
	SCREEN_ATTR_CGA_BG_LIGHT_MAGENTA = SCREEN_ATTR_CGA_FG_LIGHT_MAGENTA << 4,
	SCREEN_ATTR_CGA_BG_YELLOW        = SCREEN_ATTR_CGA_FG_YELLOW << 4,
	SCREEN_ATTR_CGA_BG_WHITE         = SCREEN_ATTR_CGA_FG_WHITE << 4,

	// note: this is only availble if blinking is enabled
	SCREEN_ATTR_BLINK = 0x80,

	// only one of these should be used, but SCREEN_ATTR_FG_LIGHT and SCREEN_ATTR_BLINK/SCREEN_ATTR_BG_LIGHT can be or'd with it
	SCREEN_ATTR_MDA_INVISIBLE = 0x00,
	SCREEN_ATTR_MDA_UNDERLINED = 0x01,
	SCREEN_ATTR_MDA_NORMAL = 0x07,
	SCREEN_ATTR_MDA_INVERTED = 0x70,
};

#endif // _COLORS_H
